/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BddDslRuntimeModule extends AbstractBddDslRuntimeModule {
}
