/*
 * generated by Xtext 2.25.0
 */
package dk.pejo.xtext.bdd_dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class BddDslWebModule extends AbstractBddDslWebModule {
}
