/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.bdd.xtext.BddDslRuntimeModule;
import dk.sdu.bdd.xtext.BddDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BddDslIdeSetup extends BddDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BddDslRuntimeModule(), new BddDslIdeModule()));
	}
	
}
