/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.ide

import com.google.inject.Guice
import dk.sdu.bdd.xtext.BddDslRuntimeModule
import dk.sdu.bdd.xtext.BddDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BddDslIdeSetup extends BddDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BddDslRuntimeModule, new BddDslIdeModule))
	}
	
}
