/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BddDslUiModule extends AbstractBddDslUiModule {

	public BddDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
