/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class BddDslWebModule extends AbstractBddDslWebModule {
}
