/*
 * generated by Xtext 2.25.0
 */
package dk.pejo.xtext.bdd_dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.pejo.xtext.bdd_dsl.BddDslRuntimeModule;
import dk.pejo.xtext.bdd_dsl.BddDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BddDslIdeSetup extends BddDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BddDslRuntimeModule(), new BddDslIdeModule()));
	}
	
}
